"""
Nifty 500 constituent symbols for pre-fetching live market data.

This list enables the market service to subscribe to all Nifty-500 stocks
on startup, ensuring instant price lookups without rate limit concerns.

Auto-generated: angelone_token_generator.py
Update frequency: Run `generate_angelone_tokens_task` to refresh
Source: NSE India official index constituents + Angel One scrip master
"""

# Nifty 500 symbols (NSE format with -EQ suffix)
# Total symbols: 500
NIFTY_500_SYMBOLS = [
    "RELIANCE-EQ", "TCS-EQ", "HDFCBANK-EQ", "INFY-EQ", "ICICIBANK-EQ",
    "HINDUNILVR-EQ", "ITC-EQ", "SBIN-EQ", "BHARTIARTL-EQ", "KOTAKBANK-EQ",
    "BAJFINANCE-EQ", "LT-EQ", "ASIANPAINT-EQ", "HCLTECH-EQ", "AXISBANK-EQ",
    "MARUTI-EQ", "SUNPHARMA-EQ", "TITAN-EQ", "ULTRACEMCO-EQ", "WIPRO-EQ",
    "NESTLEIND-EQ", "ONGC-EQ", "NTPC-EQ", "POWERGRID-EQ", "M&M-EQ",
    "BAJAJFINSV-EQ", "ADANIENT-EQ", "JSWSTEEL-EQ", "TATASTEEL-EQ", "INDUSINDBK-EQ",
    "ADANIPORTS-EQ", "COALINDIA-EQ", "HINDALCO-EQ", "DIVISLAB-EQ", "DRREDDY-EQ",
    "BAJAJ-AUTO-EQ", "TECHM-EQ", "EICHERMOT-EQ", "CIPLA-EQ", "GRASIM-EQ",
    "BRITANNIA-EQ", "TATACONSUM-EQ", "HEROMOTOCO-EQ", "BPCL-EQ", "APOLLOHOSP-EQ",
    "SBILIFE-EQ", "HDFCLIFE-EQ", "LTIM-EQ", "VEDL-EQ", "011NSETEST-EQ",
    "021NSETEST-EQ", "031NSETEST-EQ", "041NSETEST-EQ", "051NSETEST-EQ", "061NSETEST-EQ",
    "071NSETEST-EQ", "081NSETEST-EQ", "091NSETEST-EQ", "101NSETEST-EQ", "111NSETEST-EQ",
    "11NSETEST-EQ", "121NSETEST-EQ", "131NSETEST-EQ", "141NSETEST-EQ", "151NSETEST-EQ",
    "161NSETEST-EQ", "171NSETEST-EQ", "181NSETEST-EQ", "20MICRONS-EQ", "21STCENMGM-EQ",
    "360ONE-EQ", "3IINFOLTD-EQ", "3MINDIA-EQ", "3PLAND-EQ", "5PAISA-EQ",
    "63MOONS-EQ", "A2ZINFRA-EQ", "AADHARHFC-EQ", "AAKASH-EQ", "AARON-EQ",
    "AARTECH-EQ", "AARTIDRUGS-EQ", "AARTIIND-EQ", "AARTIPHARM-EQ", "AARTISURF-EQ",
    "AARVI-EQ", "AAVAS-EQ", "ABB-EQ", "ABBOTINDIA-EQ", "ABCAPITAL-EQ",
    "ABCOTS-EQ", "ABDL-EQ", "ABFRL-EQ", "ABGSEC-EQ", "ABINFRA-EQ",
    "ABLBL-EQ", "ABREL-EQ", "ABSLAMC-EQ", "ABSLBANETF-EQ", "ABSLLIQUID-EQ",
    "ABSLNN50ET-EQ", "ABSLPSE-EQ", "ACC-EQ", "ACCELYA-EQ", "ACCURACY-EQ",
    "ACE-EQ", "ACEINTEG-EQ", "ACI-EQ", "ACLGATI-EQ", "ACMESOLAR-EQ",
    "ACUTAAS-EQ", "ADANIENSOL-EQ", "ADANIGREEN-EQ", "ADANIPOWER-EQ", "ADFFOODS-EQ",
    "ADL-EQ", "ADOR-EQ", "ADROITINFO-EQ", "ADSL-EQ", "ADVANCE-EQ",
    "ADVANIHOTR-EQ", "ADVENZYMES-EQ", "AEGISLOG-EQ", "AEGISVOPAK-EQ", "AEROENTER-EQ",
    "AEROFLEX-EQ", "AERONEU-EQ", "AETHER-EQ", "AFCONS-EQ", "AFFLE-EQ",
    "AFFORDABLE-EQ", "AFIL-EQ", "AFSL-EQ", "AGARIND-EQ", "AGARWALEYE-EQ",
    "AGI-EQ", "AGIIL-EQ", "AGRITECH-EQ", "AHLADA-EQ", "AHLEAST-EQ",
    "AHLUCONT-EQ", "AIAENG-EQ", "AIIL-EQ", "AIRAN-EQ", "AIROLAM-EQ",
    "AJANTPHARM-EQ", "AJAXENGG-EQ", "AJMERA-EQ", "AJOONI-EQ", "AKASH-EQ",
    "AKG-EQ", "AKI-EQ", "AKSHARCHEM-EQ", "AKSHOPTFBR-EQ", "AKUMS-EQ",
    "AKZOINDIA-EQ", "ALANKIT-EQ", "ALBERTDAVD-EQ", "ALEMBICLTD-EQ", "ALICON-EQ",
    "ALIVUS-EQ", "ALKALI-EQ", "ALKEM-EQ", "ALKYLAMINE-EQ", "ALLCARGO-EQ",
    "ALLDIGI-EQ", "ALLTIME-EQ", "ALMONDZ-EQ", "ALOKINDS-EQ", "ALPA-EQ",
    "ALPHA-EQ", "ALPHAETF-EQ", "ALPHAGEO-EQ", "ALPL30IETF-EQ", "AMANTA-EQ",
    "AMBER-EQ", "AMBICAAGAR-EQ", "AMBIKCO-EQ", "AMBUJACEM-EQ", "AMDIND-EQ",
    "AMJLAND-EQ", "AMNPLST-EQ", "AMRUTANJAN-EQ", "ANANDRATHI-EQ", "ANANTRAJ-EQ",
    "ANDHRAPAP-EQ", "ANDHRSUGAR-EQ", "ANGELONE-EQ", "ANIKINDS-EQ", "ANMOL-EQ",
    "ANTELOPUS-EQ", "ANTGRAPHIC-EQ", "ANTHEM-EQ", "ANUHPHR-EQ", "ANUP-EQ",
    "ANURAS-EQ", "AONEGOLD-EQ", "AONELIQUID-EQ", "AONENIFTY-EQ", "AONETOTAL-EQ",
    "APARINDS-EQ", "APCL-EQ", "APCOTEXIND-EQ", "APEX-EQ", "APLAPOLLO-EQ",
    "APLLTD-EQ", "APOLLO-EQ", "APOLLOPIPE-EQ", "APOLLOTYRE-EQ", "APOLSINHOT-EQ",
    "APTECHT-EQ", "APTUS-EQ", "ARCHIDPLY-EQ", "ARCHIES-EQ", "ARE&M-EQ",
    "ARENTERP-EQ", "ARIES-EQ", "ARIHANTCAP-EQ", "ARIHANTSUP-EQ", "ARISINFRA-EQ",
    "ARKADE-EQ", "ARMANFIN-EQ", "AROGRANITE-EQ", "ARROWGREEN-EQ", "ARSSBL-EQ",
    "ARTEMISMED-EQ", "ARTNIRMAN-EQ", "ARVEE-EQ", "ARVIND-EQ", "ARVINDFASN-EQ",
    "ARVSMART-EQ", "ASAHIINDIA-EQ", "ASAHISONG-EQ", "ASAL-EQ", "ASALCBR-EQ",
    "ASHAPURMIN-EQ", "ASHIANA-EQ", "ASHIMASYN-EQ", "ASHOKA-EQ", "ASHOKAMET-EQ",
    "ASHOKLEY-EQ", "ASIANENE-EQ", "ASIANHOTNR-EQ", "ASIANTILES-EQ", "ASKAUTOLTD-EQ",
    "ASPINWALL-EQ", "ASTEC-EQ", "ASTERDM-EQ", "ASTRAL-EQ", "ASTRAMICRO-EQ",
    "ASTRAZEN-EQ", "ASTRON-EQ", "ATALREAL-EQ", "ATAM-EQ", "ATGL-EQ",
    "ATHERENERG-EQ", "ATL-EQ", "ATLANTAELE-EQ", "ATLASCYCLE-EQ", "ATUL-EQ",
    "ATULAUTO-EQ", "AUBANK-EQ", "AURIGROW-EQ", "AURIONPRO-EQ", "AUROPHARMA-EQ",
    "AURUM-EQ", "AUSOMENT-EQ", "AUTOAXLES-EQ", "AUTOBEES-EQ", "AUTOIETF-EQ",
    "AUTOIND-EQ", "AVADHSUGAR-EQ", "AVALON-EQ", "AVANTEL-EQ", "AVANTIFEED-EQ",
    "AVG-EQ", "AVL-EQ", "AVONMORE-EQ", "AVROIND-EQ", "AVTNPL-EQ",
    "AWFIS-EQ", "AWHCL-EQ", "AWL-EQ", "AXISBNKETF-EQ", "AXISBPSETF-EQ",
    "AXISCETF-EQ", "AXISGOLD-EQ", "AXISHCETF-EQ", "AXISILVER-EQ", "AXISNIFTY-EQ",
    "AXISTECETF-EQ", "AXISVALUE-EQ", "AXITA-EQ", "AXSENSEX-EQ", "AYMSYNTEX-EQ",
    "AZAD-EQ", "BAGFILMS-EQ", "BAIDFIN-EQ", "BAJAJCON-EQ", "BAJAJELEC-EQ",
    "BAJAJHCARE-EQ", "BAJAJHFL-EQ", "BAJAJHIND-EQ", "BAJAJHLDNG-EQ", "BAJAJINDEF-EQ",
    "BAJEL-EQ", "BALAJEE-EQ", "BALAJITELE-EQ", "BALAMINES-EQ", "BALAXI-EQ",
    "BALKRISHNA-EQ", "BALKRISIND-EQ", "BALMLAWRIE-EQ", "BALPHARMA-EQ", "BALRAMCHIN-EQ",
    "BALUFORGE-EQ", "BANARBEADS-EQ", "BANARISUG-EQ", "BANCOINDIA-EQ", "BANDHANBNK-EQ",
    "BANG-EQ", "BANKA-EQ", "BANKBARODA-EQ", "BANKBEES-EQ", "BANKBETF-EQ",
    "BANKETF-EQ", "BANKETFADD-EQ", "BANKIETF-EQ", "BANKINDIA-EQ", "BANKNIFTY1-EQ",
    "BANKPSU-EQ", "BANSALWIRE-EQ", "BANSWRAS-EQ", "BASF-EQ", "BASML-EQ",
    "BATAINDIA-EQ", "BAYERCROP-EQ", "BBETF0432-EQ", "BBL-EQ", "BBNPNBETF-EQ",
    "BBNPPGOLD-EQ", "BBOX-EQ", "BBTC-EQ", "BBTCL-EQ", "BCG-EQ",
    "BCLIND-EQ", "BDL-EQ", "BEARDSELL-EQ", "BECTORFOOD-EQ", "BEDMUTHA-EQ",
    "BEL-EQ", "BELLACASA-EQ", "BELRISE-EQ", "BEML-EQ", "BEPL-EQ",
    "BERGEPAINT-EQ", "BESTAGRO-EQ", "BFINVEST-EQ", "BFSI-EQ", "BHAGCHEM-EQ",
    "BHAGERIA-EQ", "BHAGYANGR-EQ", "BHANDARI-EQ", "BHARATFORG-EQ", "BHARATRAS-EQ",
    "BHARATSE-EQ", "BHARATWIRE-EQ", "BHARTIHEXA-EQ", "BHEL-EQ", "BIGBLOC-EQ",
    "BIKAJI-EQ", "BIL-EQ", "BILVYAPAR-EQ", "BIOCON-EQ", "BIOFILCHEM-EQ",
    "BIRLACABLE-EQ", "BIRLACORPN-EQ", "BIRLAMONEY-EQ", "BIRLANU-EQ", "BLACKBUCK-EQ",
    "BLAL-EQ", "BLBLIMITED-EQ", "BLISSGVS-EQ", "BLKASHYAP-EQ", "BLS-EQ",
    "BLSE-EQ", "BLUEDART-EQ", "BLUEJET-EQ", "BLUESTARCO-EQ", "BLUESTONE-EQ",
    "BLUSPRING-EQ", "BMWVENTLTD-EQ", "BODALCHEM-EQ", "BOHRAIND-EQ", "BOMDYEING-EQ",
    "BORANA-EQ", "BOROLTD-EQ", "BORORENEW-EQ", "BOROSCI-EQ", "BOSCHLTD-EQ",
    "BPL-EQ", "BRIGADE-EQ", "BRIGHOTEL-EQ", "BRNL-EQ", "BROOKS-EQ",
    "BSE-EQ", "BSE500IETF-EQ", "BSHSL-EQ", "BSL-EQ", "BSLGOLDETF-EQ",
    "BSLNIFTY-EQ", "BSLSENETFG-EQ", "BSOFT-EQ", "BTML-EQ", "BUTTERFLY-EQ",
    "BYKE-EQ", "CALSOFT-EQ", "CAMLINFINE-EQ", "CAMPUS-EQ", "CAMS-EQ",
    "CANBK-EQ", "CANFINHOME-EQ", "CANHLIFE-EQ", "CANTABIL-EQ", "CAPACITE-EQ",
    "CAPITALSFB-EQ", "CAPLIPOINT-EQ", "CAPTRUST-EQ", "CARBORUNIV-EQ", "CARERATING-EQ",
    "CARRARO-EQ", "CARTRADE-EQ", "CARYSIL-EQ", "CASHIETF-EQ", "CASTROLIND-EQ",
    "CCHHL-EQ", "CCL-EQ", "CDSL-EQ", "CEATLTD-EQ", "CEIGALL-EQ",
    "CELEBRITY-EQ", "CELLO-EQ", "CEMPRO-EQ", "CENTENKA-EQ", "CENTRALBK-EQ",
    "CENTRUM-EQ", "CENTUM-EQ", "CENTURYPLY-EQ", "CERA-EQ", "CESC-EQ",
    "CEWATER-EQ", "CGCL-EQ", "CGPOWER-EQ", "CHALET-EQ", "CHAMBLFERT-EQ",
    "CHEMBOND-EQ", "CHEMBONDCH-EQ", "CHEMCON-EQ", "CHEMFAB-EQ", "CHEMPLASTS-EQ",
    "CHENNPETRO-EQ", "CHEVIOT-EQ", "CHOICEIN-EQ", "CHOLAFIN-EQ", "CHOLAHLDNG-EQ",
    "CIEINDIA-EQ", "CIFL-EQ", "CIGNITITEC-EQ", "CINELINE-EQ", "CINEVISTA-EQ",
    "CLEAN-EQ", "CLSEL-EQ", "CMSINFO-EQ", "COASTCORP-EQ", "COCHINSHIP-EQ",
    "COFORGE-EQ", "COHANCE-EQ", "COLPAL-EQ", "COMMOIETF-EQ", "COMPUSOFT-EQ",
    "COMSYN-EQ", "CONCOR-EQ", "CONCORDBIO-EQ", "CONFIPET-EQ", "CONS-EQ",
    "CONSOFINVT-EQ", "CONSUMBEES-EQ", "CONSUMER-EQ", "CONSUMIETF-EQ", "CONTROLPR-EQ",
    "CORALFINAC-EQ", "CORDSCABLE-EQ", "COROMANDEL-EQ", "COSMOFIRST-EQ", "COUNCODOS-EQ",
    "CPCAP-EQ", "CPEDU-EQ", "CPPLUS-EQ", "CPSEETF-EQ", "CRAFTSMAN-EQ",

]

def get_nifty500_symbols() -> list[str]:
    """Return list of Nifty 500 constituent symbols."""
    return NIFTY_500_SYMBOLS.copy()

def get_nifty500_count() -> int:
    """Return count of Nifty 500 symbols."""
    return len(NIFTY_500_SYMBOLS)
